baseURL = "https://tliangyuw.github.io/kyoto-2026/"
languageCode = "zh-tw"
title = "Liang-Yu | 2026 京都之旅"
theme = "blowfish"

[params]
  showSummary = true
  # 讓首頁能夠正確讀取 content 目錄下的內容
  homepage = { layout = "profile" }