baseURL = "https://tliangyuw.github.io/kyoto-2026/"
languageCode = "zh-tw"
title = "Liang-Yu | 2026 京都之旅"
theme = "blowfish"

[params]
showSummary = false
  # 將首頁版型改為 "page"，這樣它就只會顯示 _index.md 的內容
  homepage = { layout = "page" }