baseURL = "https://tliangyuw.github.io/kyoto-2026/"
languageCode = "zh-tw"
title = "Liang-Yu | 2026 京都之旅"
theme = "blowfish"

[params]
  showSummary = false
  # 將首頁改為單一頁面模式，防止自動抓取文章
  homepage = { layout = "page" }